# 单机单zookeeper 单kafak

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2

      # docker host IP
      KAFKA_ADVERTISED_HOST_NAME: 192.195.24.157
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./log:/kafka