global:
  resolve_timeout: 5m

route:
  receiver: wechat
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  group_by: [alertname]
  routes:
  - receiver: dding-webhook
    group_wait: 10s

receivers:
- name: dding-webhook
  webhook_configs:
  - url: http://10.0.0.37:8081/ping