prome:
  image: prom/prometheus-linux-arm64
  container_name: prometheus
  restart: always
  net: host
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./rules:/rules
  environment:
    - TZ=Asia/Shanghai

alert:
  image: docker.io/prom/alertmanager
  container_name: alert-manager
  restart: always
  net: host
  volumes:
    - ./alertmanager.yml:/etc/alertmanager.yml
    # - ./alertmanager.tmpl:/etc/alertmanager.tmpl
  environment:
    - TZ=Asia/Shanghai
    - Update=20220309
  command:
    --config.file=/etc/alertmanager.yml

client:
  image: docker.sixun.hw:5000/siss/node-exporter-linux-arm64:latest
  container_name: prome-node
  restart: always
  privileged: true
  net: host
  volumes:
    - /backup:/backup
  environment:
    - TZ=Asia/Shanghai

# Auto Discovery
consul:
  image: consul
  container_name: prome-consule
  restart: always
  net: host
  volumes:
    - ./consul_data:/consul/data
  environment:
    - TZ=Asia/Shanghai
  command:
    consul agent -dev -ui -data-dir=/consul/data -client 0.0.0.0 
    # consul agent -server -data-dir=/data/consul -bind= -ui -client=0.0.0.0 

webhook:
  image: webhook-dding
  container_name: webhook-dding
  restart: always
  ports:
    - 8081:8080
  volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  environment:
    - TZ=Asia/Shanghai
    - GIN_MODE=release
    - SKIPS=log:内存,es:内存,ops:内存,localhost:内存
    - DDING_TOKEN=Token

# Dashboard
grafana:
  image: grafana/grafana
  container_name: grafana
  restart: always
  net: host
  environment:
    - TZ=Asia/Shanghai
  volumes:
    - ./grafana_data:/var/lib/grafana