# 单节点主机副本集
version: "2"

services:
  db_a:
    image: mongo:3.4
    restart: always
    # ports:
    #   - "27017:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db/db_a/data:/data/db
      - ./db/db_a/log:/data/log
    command: mongod  --replSet rs0  --dbpath /data/db --port 27017 --logpath /data/log/db.log
  ## 下方配置实现一台机器副本集
    network_mode: "host"


  db_b:
    image: mongo:3.4
    restart: always
    # ports:
    #   - "27018:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db/db_b/data:/data/db
      - ./db/db_b/log:/data/log
    command: mongod  --replSet rs0  --dbpath /data/db --port 27018 --logpath /data/log/db.log
    network_mode: "host"

  db_c:
    image: mongo:3.4
    restart: always
    # ports:
    #   - "27019:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db/db_c/data:/data/db
      - ./db/db_c/log:/data/log
    command: mongod  --replSet rs0  --dbpath /data/db --port 27019 --logpath /data/log/db.log
    network_mode: "host"

# mkdir -p ./db/db_a/data
# mkdir -p ./db/db_b/data
# mkdir -p ./db/db_c/data
# mkdir -p ./db/db_a/log
# mkdir -p ./db/db_b/log
# mkdir -p ./db/db_c/log
# chown 999 -R ./db
# sed -i 's/^SELINUX=.*/SELINUX=disabled/g'  /etc/selinux/config
# setenforce 0