# 单节点
mongo:
  image: mongo:4
  net: host
  restart: always
  environment:
    - TZ=Asia/Shanghai
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./db:/data/db:z

# mkdir ./db
# chown 999 -R ./db
# sed -i 's/^SELINUX=.*/SELINUX=disabled/g'  /etc/selinux/config
# setenforce 0

# systemctl is-active firewalld &>/dev/null && firewall-cmd --add-port=27017/tcp --permanent && systemctl restart firewalld
# systemctl is-active iptables &>/dev/null && iptables -I INPUT 4 -p tcp  -m state --state NEW --dport 27017 -j ACCEPT && service iptables save
