# 单点
fastdfs:
  image: docker.vpclub.cn/fastdfs
  restart: always
  environment:
    - WEB_PORT=8200
  volumes:
    - ./data:/var/local/fdfs
  # 使docker具有root权限以读写主机上的目录
  ports:
    - 22122:22122
    - 8200:8200
    - 23000:23000