nginx:
  image: nginx
  restart: always
  container_name: nginx
  ports:
    - "8080:80"
    - "8443:443"
  environment:
    - TZ="Asia/Shanghai"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    # nginx configure
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./mysite.conf:/etc/nginx/conf.d/default.conf:ro
    # - ./ssl:/etc/nginx/conf/ssl:ro
    # log save folder
    - ./logs:/var/log/nginx/
    # -------------------site configure -------------
    # site file
    # - ./ram-space/dist:/usr/share/nginx/html:ro
    # - ./dist:/usr/share/nginx/html:ro