cassandra:
  image: cassandra:3.9
  container_name: cassandra
  net: "host"
  environment:
    # 其它加入集群的Cassadra，则取取消下面注释
    # - CASSANDRA_SEEDS=172.16.11.1
    - CASSANDRA_BROADCAST_ADDRESS=172.16.11.1
    - CASSANDRA_LISTEN_ADDRESS=172.16.11.1
    - MAX_HEAP_SIZE=500M
    - HEAP_NEWSIZE=100M
  volumes:
    - ./hosts:/etc/hosts
    - ./data:/var/lib/cassandra
